package com.example.Backend.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.data.annotation.Id;

import java.time.LocalDateTime;

/*
    code taken from Kotlin:

    ```
//    Habit:
//
//    id: int, or UID A unique identifier for each habit, automatically generated by the system. Not visible to the user.
//
//    name: string The descriptive name of the habit (e.g., "Exercise", "Smoking").
//
//    type: string Indicates the nature of the habit, whether it is good, bad, or neutral (other).
//
//    description: string? A detailed explanation of the habit, outlining what it entails. Nullable.
//
//    frequency: string Defines how often the habit should be tracked, such as daily, weekly, or monthly.
//
//    label: string A category or tag that describes the general nature of the habit (e.g., healthy, unhealthy, Wellness, routine).
//
//    target: string? The goal or objective associated with the habit, such as the duration, amount, or specific aim. Nullable.
//
//    createdAt: LocalDateTime The date and time when the habit was created. Not visible to the user.

@Entity(tableName = "habit")
data class Habit (
    // make autoincrement
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    // val id: Int,
    var name: String,
    var type: String,
    var description: String?,
    var frequency: String,
    var label: String,
    var target: String,
    var createdAt: LocalDateTime
)
    ```
 */

@Entity
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Habit {
    @jakarta.persistence.Id
    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String type;
    private String description;
    private String frequency;
    private String label;
    private String target;
    @CreationTimestamp
    @Column(nullable = false, name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Override
    public String toString() {
        return "Habit{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", label='" + label + '\'' +
                ", type='" + type + '\'' +
                ", frequency='" + frequency + '\'' +
                ", target='" + target + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
