spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/habittrackerdb
spring.datasource.username=mobile
spring.datasource.password=mobile

# JDBC Driver for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB

# Hibernate (JPA) Configuration
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled=false


# Connection Pool Configuration (Optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

server.address=0.0.0.0
server.port=8080